### ISSUE TITLE
How to restart the mongod server?

### ISSUE THREAD

**Issue by lx1054331851** [michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide#30]
The command "sudo systemctl restart mongod" or "sudo restart mongod" did not work.

**Comment by bossyahrul** [comment]
I found these note at https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-database:

"You might see the command sudo systemctl status mongodb used in tutorials or articles. In order to remain lightweight, WSL does not include systemd (a service management system in Linux). Instead, it uses SysVinit to start services on your machine. You shouldn't notice a difference, but if a tutorial recommends using sudo systemctl, instead use: sudo /etc/init.d/. For example, sudo systemctl status mongodb, for WSL would be sudo /etc/inid.d/mongodb status ...or you can also use sudo service mongodb status."

Hope this helps!

**Comment by michaeltreat** [comment]
@lx1054331851 Did this solve your issue?
